version: "2"
services:
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ahT2InegE3aM
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  app:
    build: ./webapp
    links:
      - db
    ports:
      - "5000:5000"
